# Generated by Django 4.0.1 on 2022-05-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=20, null=True),
        ),
    ]
