# Generated by Django 4.0.1 on 2022-05-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_profile_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='date',
        ),
    ]
